
// Objective-C API for talking to the following Go packages
//
//	tsembed
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TailscaleEmbed_FRAMEWORK_H__
#define __TailscaleEmbed_FRAMEWORK_H__

#include "Tsembed.objc.h"
#include "Universe.objc.h"

#endif
