// Objective-C API for talking to tsembed Go package.
//   gobind -lang=objc tsembed
//
// File is generated by gobind. Do not edit.

#ifndef __Tsembed_H__
#define __Tsembed_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TsembedTailscale;

/**
 * Tailscale wraps tsnet.Server and provides an HTTP proxy for routing traffic.
 */
@interface TsembedTailscale : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTailscale creates a new Tailscale instance with the given state
directory, auth key, and tailnet hostname for the embedded node.
 */
- (nullable instancetype)init:(NSString* _Nullable)stateDir authKey:(NSString* _Nullable)authKey hostname:(NSString* _Nullable)hostname;
/**
 * EnsureProxy verifies the local proxy listener is still accepting
connections (iOS reclaims sockets during app suspension) and rebinds it on
a fresh port if it died. Returns the current (possibly new) proxy port.
 */
- (BOOL)ensureProxy:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * GetPort returns the current proxy port, or 0 if not running.
 */
- (long)getPort;
/**
 * IsRunning returns whether the proxy is currently running.
 */
- (BOOL)isRunning;
/**
 * StartProxy starts the tsnet server and HTTP proxy, returning the proxy port.
 */
- (BOOL)startProxy:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * StopProxy stops the HTTP proxy and tsnet server.
 */
- (void)stopProxy;
@end

/**
 * NewTailscale creates a new Tailscale instance with the given state
directory, auth key, and tailnet hostname for the embedded node.
 */
FOUNDATION_EXPORT TsembedTailscale* _Nullable TsembedNewTailscale(NSString* _Nullable stateDir, NSString* _Nullable authKey, NSString* _Nullable hostname);

#endif
